# For Backend Repository (docker-compose.yml)
version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: weid-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=weid
    volumes:
      - mongodb_data:/data/db
    networks:
      - weid-network
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/weid --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weid-backend
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/weid
      - JWT_SECRET=development_jwt_secret_change_in_production
      - JWT_EXPIRATION=24h
      - JWT_REFRESH_SECRET=development_refresh_secret_change_in_production
      - JWT_REFRESH_EXPIRATION=7d
      - CLIENT_URL=http://localhost:3000
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - weid-network
    restart: unless-stopped
    command: npm run dev

networks:
  weid-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local